language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install nose --use-mirrors
  - pip install coverage --use-mirrors
  - pip install django_nose --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python runtests.py
